Update to use esptool-js
adafruit/Adafruit_WebSerial_ESPTool pull request #311
Opened 2024-12-04 18:04 UTC by makermelissa

This PR completely guts the ESPTool that did the programming and replaces the underlying code with esptool-js while still retaining the same user interface. This should be a 2.0.0 release, though since nothing is compiled anymore, that isn't strictly necessary.

I also took into account the passthrough option (which wasn't saving the setting anymore) when updating.

cc @dhalbert and @ladyada for review

2024-12-04 20:07 UTC, dhalbert requested changes
I think too many files were deleted, including `README.md`, `package.json`, etc.?

2024-12-04 20:09 UTC, ladyada commented
ok thanks @tyeth can test it!

2024-12-04 22:30 UTC, makermelissa commented
All typescript and related files were removed because the that functionality is now handled by esptool-js.

2024-12-04 22:59 UTC, dhalbert requested changes
Some changes requested to the README.

I tested with a Feather ESP32-C6, a QT Py ESP32-C3, and a QT Py ESP32-S3.

C6:
```
Erasing flash (this may take a while)...
Error: Error: Timeout
```
But on the old one, it doesn't even get that far. So maybe there is still a problem with C6 support in the Espressif tools.

C3 and S3 work fine.

2024-12-04 22:59 UTC, dhalbert commented on README.md
> +- Install dependencies with `npm`
There are no dependencies. Running `npm install` causes an error.
```suggestion
```

2024-12-04 22:59 UTC, dhalbert commented on README.md
> +This project was originally written by [Melissa LeBlanc-Williams](https://github.com/makermelissa). [Nabu Casa](https://www.nabucasa.com) ported the code over to TypeScript and in March 2022 took ove
This is out of date now.

2024-12-04 23:41 UTC, tyeth commented
Pyportal titano looks good
The fun house (s2) times out, but it's been fixed in latest esptool-js main
branch (pr160) so I've asked them to release it so unpkg gets updated.

On Wed, 4 Dec 2024, 22:59 Dan Halbert, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Some changes requested to the README.
>
> I tested with a Feather ESP32-C6, a QT Py ESP32-C3, and a QT Py ESP32-S3.
>
> C6:
>
> Erasing flash (this may take a while)...
> Error: Error: Timeout
>
> But on the old one, it doesn't even get that far. So maybe there is still
> a problem with C6 support in the Espressif tools.
>
> C3 and S3 work fine.
> ------------------------------
>
> In README.md
> <https://github.com/adafruit/Adafruit_WebSerial_ESPTool/pull/311#discussion_r1870379295>
> :
>
> > @@ -0,0 +1,22 @@
> +# Adafruit WebSerial ESPTool
> +
> +JavaScript package to install firmware on ESP devices via the browser using WebSerial.
> +
> +## Used by
> +
> +- [Adafruit WipperSnapper](https://learn.adafruit.com/quickstart-adafruit-io-wippersnapper)
> +- [Adafruit CircuitPython Installer](https://circuitpython.org/downloads)
> +
> +## Local development
> +
> +- Clone this repository.
> +- Install dependencies with `npm`
>
> There are no dependencies. Running npm install causes an error.
> ⬇️ Suggested change
>
> -- Install dependencies with `npm`
>
> ------------------------------
>
> In README.md
> <https://github.com/adafruit/Adafruit_WebSerial_ESPTool/pull/311#discussion_r1870379464>
> :
>
> > +
> +## Used by
> +
> +- [Adafruit WipperSnapper](https://learn.adafruit.com/quickstart-adafruit-io-wippersnapper)
> +- [Adafruit CircuitPython Installer](https://circuitpython.org/downloads)
> +
> +## Local development
> +
> +- Clone this repository.
> +- Install dependencies with `npm`
> +- Run `script/develop`
> +- Open http://localhost:5004/
> +
> +## Origin
> +
> +This project was originally written by [Melissa LeBlanc-Williams](https://github.com/makermelissa). [Nabu Casa](https://www.nabucasa.com) ported the code over to TypeScript and in March 2022 took over maintenance from Adafruit. In July 2022, the Nabucasa stopped maintaining the project in favor of an official, but very early release of Espressif's [esptool-js](https://github.com/espressif/esptool-js/). Due to the instability of the tool, Adafruit updated their fork with Nabucasa's changes in November 2022 and took over maintenance once again.
>
> This is out of date now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_WebSerial_ESPTool/pull/311#pullrequestreview-2480067734>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABTBZ47VLA77FV65ZJDTANL2D6CNHAVCNFSM6AAAAABTAX3SW2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBQGA3DONZTGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-12-05 00:14 UTC, ladyada commented
thanks, thats a good testbed

2024-12-09 16:28 UTC, tyeth commented
Just a heads up that there is a minor delay on release for this C3 issue, but the fix went in today, so imagining a release tomorrow / wednesday: https://github.com/espressif/esptool-js/issues/161#issuecomment-2527316667

2024-12-10 14:19 UTC, tyeth commented
@makermelissa v0.5.2 of esptool-js has been released.

2024-12-10 18:13 UTC, tyeth commented
-Edit- It's got issues, atob fails when processing the stub, must be some bundling issue. When I run esptool-js's example and build to a site it works fine, but that doesn't use the cdn bundle (it uses the individually split files), I've filed a report: https://github.com/espressif/esptool-js/issues/167

2024-12-10 22:41 UTC, makermelissa commented
Ok, I'll keep watching. It should point to the latest bundle automatically, but we can point it somewhere else besides the bundle if needed.

2024-12-17 23:29 UTC, makermelissa commented
I have tied the esptool-js to version 0.5.1, which tested while working on the CircuitPython Installer so it won't break unexpectedly on us again.

2024-12-18 03:21 UTC, dhalbert requested changes
Just some README fixups requested.

2024-12-18 03:21 UTC, dhalbert commented on README.md
> +This project was originally written by [Melissa LeBlanc-Williams](https://github.com/makermelissa). [Nabu Casa](https://www.nabucasa.com) ported the code over to TypeScript and in March 2022 took ove
Update this history to say we went back to the Espressif version (or just remove the detailed history).

2024-12-18 03:21 UTC, dhalbert commented on README.md
> +- Install dependencies with `npm`
Remove this line since there are no dependencies anymore.

2024-12-18 19:55 UTC, makermelissa commented
> Just some README fixups requested.

Great suggestions. I'll update it.

2024-12-18 21:13 UTC, dhalbert approved these changes
Looks great!

2024-12-18 21:13 UTC, merged